### ISSUE TITLE
Any way to restore the zoomed image?

### ISSUE THREAD

**Issue by emreavsar** [huynguyencong/ImageScrollView#11]
Hi there,

is there any way to restore the images zoomscale and contentoffset after re-setting the image, so that the user does not lose the zoomed image when re-opening the view?

I tried to save the zoomScale and contentOffset on viewDidDissappear and re-setting it after using your displayImage() with myScrollImageView.zoomScale = savedZoomScale and the same for contentoffset but it does not work.

Any ideas for that?

cheers and thanks for the nice library!
emre

**Comment by emreavsar** [comment]
Ah sorry my mistake, i did a displayImage after that somewhere in my code again. :) works now.

**Comment by wdcurry** [comment]
A tweak i added locally to allow me to preset zoom/offset on load, with no effort to make this entirely efficient:
  
        @objc open func display(image: UIImage, offset: CGPoint, zoom: CGFloat) {
        
        if let zoomView = zoomView {
            zoomView.removeFromSuperview()
        }
        
        zoomView = UIImageView(image: image)
        zoomView!.isUserInteractionEnabled = true
        addSubview(zoomView!)
        
        let tapGesture = UITapGestureRecognizer(target: self, action: #selector(ImageScrollView.doubleTapGestureRecognizer(_:)))
        tapGesture.numberOfTapsRequired = 2
        zoomView!.addGestureRecognizer(tapGesture)
        
        configureImageForSize(image.size)
        
        //reset image
        self.contentOffset = offset
        self.zoomScale = zoom
        
    }
