### ISSUE TITLE
<Error>: CGAffineTransformInvert: singular matrix.

### ISSUE THREAD

**Issue by luisbarajasp** [huynguyencong/ImageScrollView#12]
Hello,

I am implementing your class and I found it great and very easy to implement but I have the issue mentioned in the title that displays in the console twice each image that I load. Also only the first image gets render the others does not appear. 

I am using the file because I have some issues with CocoaPods and I implemented it on a collectionView with custom cells in horizontal layout. Here is the code:

In the cell:
`var albumItem: AlbumItem? {
        didSet{
            
            let image = UIImage(named: (albumItem?.imageName)!)
            
            imageView.display(image: image!)
            
            if albumItem?.type == .video {
                setUpPlayImage()
            }
            
        }
    }
    
    let imageView: ImageScrollView = {
        let iv = ImageScrollView()
        let image = UIImage(named: "chiron")
        iv.display(image: image!)
        iv.zoomView?.contentMode = .scaleAspectFill
        iv.clipsToBounds = true
        iv.translatesAutoresizingMaskIntoConstraints = false
        return iv
    }()`
In the CollectionViewcontroller:

`override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let singleTap = UITapGestureRecognizer()
        singleTap.numberOfTapsRequired = 1
        //singleTap.require(toFail: doubleTap)
        singleTap.addTarget(self, action: #selector(self.handleTap(gesture:)))
            
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: reuseIdentifier, for: indexPath) as! AlbumItemFullCell
            
        // Configure the cell
        cell.albumItem = albumItems?[indexPath.item]
        cell.playImage.contentMode = .center
        
        cell.backgroundColor = UIColor.getDarkGray()
        
        cell.addGestureRecognizer(singleTap)
        
            
        return cell
        
    }`

I noticed the part that the error gets called:

![captura de pantalla 2017-01-03 a la s 20 47 19](https://cloud.githubusercontent.com/assets/13513062/21630424/b6f015ce-d1f6-11e6-9c86-32e1465cea77.png)
![captura de pantalla 2017-01-03 a la s 20 47 44](https://cloud.githubusercontent.com/assets/13513062/21630425/b7049652-d1f6-11e6-992f-791ffb1cf1c8.png)

But I have no idea why, hope someone know whats happening.

**Comment by cogentParadigm** [comment]
I encountered the same issue. I was calling display(image:UIImage) before displaying the controller. Now I am calling it from viewDidAppear in the controller containing the ImageScrollView and that works.

**Comment by huynguyencong** [comment]
Yes, please call `display(image:UIImage)` in `viewDidLoad` or `viewDidAppear`
