### ISSUE TITLE
Image is not centered on screen after device rotation

### ISSUE THREAD

**Issue by rajathooja** [huynguyencong/ImageScrollView#16]
Swift 3, Xcode 8, iPhone 6S+, iOS 10.3.3

From your Demo project, the image is not centered on the screen after the device is rotated to and from portrait and landscape mode.

It appears to be that the scrollView is not updating it's size when orientation changes.

![2017-09-03 12 29 55](https://user-images.githubusercontent.com/30729195/30001212-9fe6fb96-90a4-11e7-8a24-fa2043c71e07.png)
![2017-09-03 12 29 58](https://user-images.githubusercontent.com/30729195/30001213-9fe79dd0-90a4-11e7-94e4-168fdbbac094.png)
![2017-09-03 12 30 05](https://user-images.githubusercontent.com/30729195/30001214-9fe81fe4-90a4-11e7-9a70-6a966deed09f.png)
![2017-09-03 12 30 08](https://user-images.githubusercontent.com/30729195/30001215-9ff3cd26-90a4-11e7-9c36-47f0d7f94816.png)

**Comment by huynguyencong** [comment]
I just fixed it. Please update new version! Thanks for your report
