### ISSUE TITLE
Objective-C Support

### ISSUE THREAD

**Issue by jruston** [huynguyencong/ImageScrollView#17]
Hey,

Nice work on this library. Your library used to work great for Objective-C but it seems to have been broken in one of the latest commits. This happened when you changed to Swift 4.

The displayWithImage method is no longer accessible in Objective-C in its current state. Luckily I was able to fix it just by adding @objc to that method in your code. You might want to add that yourself.

I would submit a pull request but I'm a little low on time :)

Thanks!

**Comment by arorajatin** [comment]
I could take it up @huynguyencong

**Comment by arorajatin** [comment]
I'll send a PR by the weekend.

**Comment by huynguyencong** [comment]
Yes, please submit a pull request. Thank you

**Comment by arorajatin** [comment]
The fix is available in PR https://github.com/huynguyencong/ImageScrollView/pull/19.

**Comment by huynguyencong** [comment]
@arorajatin  I have just merged your pull request. Thank you for your contribution. Sorry for late respond.
Thank @jrustonapps
