### ISSUE TITLE
Image not centered initially

### ISSUE THREAD

**Issue by pateljay43** [huynguyencong/ImageScrollView#18]
When image width is smaller than screen width, it aligns to the left of the screen initially.

**Comment by Mahan3340** [comment]
++

**Comment by danya0365** [comment]
+++

**Comment by sw-tt-jethanandnandpal** [comment]
Before set image add this line **self.view.layoutIfNeeded()** in viewDidLoad() method. It will resolved issue.

@IBOutlet weak var myScroll:  ImageScrollView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.view.layoutIfNeeded()
        if let helpImage = UIImage(named: "myImage") {
            myScroll.display(image: helpImage)
        }
    }

**Comment by Mahan3340** [comment]
@sw-tt-jethanandnandpal thx this fixed the problem

**Comment by huynguyencong** [comment]
Thank @sw-tt-jethanandnandpal
