### ISSUE TITLE
Imperfect auto-resizing after zooming out too far

### ISSUE THREAD

**Issue by owenbirdsall** [huynguyencong/ImageScrollView#2]
This is a very minor issue, but it would be nice when the scale is reset after zooming out too far (when the image is smaller than the frame), if the reset zoom could be pivoted from the centre of the screen rather than the top left - as it looks a bit odd at the moment.

**Comment by huynguyencong** [comment]
Sorry, I don't understand what you mean. Can you give me an example project, or animated image?

**Comment by alexander-larsson** [comment]
It is quite easy to see what he means. Just zoom out an image and release so that it bounces back. It will reposition to the top left corner and then zoom back in. It would look nicer if it zoomed back in from the current position or center.

**Comment by huynguyencong** [comment]
OK, let me try

**Comment by huynguyencong** [comment]
Fixed it. Please update new pod version 1.2
