### ISSUE TITLE
Set image content mode

### ISSUE THREAD

**Issue by ibhavin** [huynguyencong/ImageScrollView#22]
How to set image content mode?

I have tried to set image content mode to centre here:
```
open func display(image: UIImage) {
        .
        .
        .
        zoomView = UIImageView(image: image)
        zoomView?.contentMode = .center
        .
        .
        .
    }
```

But image is not displaying center.

**Comment by huynguyencong** [comment]
The image is always center. Could you show me how your image is displayed?

**Comment by ibhavin** [comment]
Image displaying normal while I set content mode to centre: 
`zoomView?.contentMode = .center`
![img_0403](https://user-images.githubusercontent.com/16459948/38790220-450127b4-415d-11e8-81e1-8a31efdae59f.PNG)



If I zoomScale manually then it display zoomed image from left:
`imageScrollView.zoomScale = 2.0`
![img_0404](https://user-images.githubusercontent.com/16459948/38790221-49fa066e-415d-11e8-9b4d-edad156d486c.PNG)

**Comment by huynguyencong** [comment]
I've just updated source code to version 1.5, which added new property `imageContentMode` and `initialOffset`. Please add the code below to get result as your expectation:

```
imageScrollView.imageContentMode = .aspectFit
imageScrollView.initialOffset = .center
```

**Comment by ibhavin** [comment]
Image still not zoomed from centre it zoomed from left side.

```
override func viewDidLoad() {
        super.viewDidLoad()

        imageScrollView.display(image: #imageLiteral(resourceName: "floorplan"))
        imageScrollView.imageContentMode = . aspectFit
        imageScrollView.initialOffset = .center

        imageScrollView.zoomScale = 2.0
        
        imageScrollView.layoutIfNeeded()
        self.view.layoutIfNeeded()
    }
```

**I want to image zoomed when it displayed:**
![simulator screen shot - iphone 8 - 2018-07-09 at 10 21 44](https://user-images.githubusercontent.com/16459948/42431286-2ad10ebc-8362-11e8-9941-c1506498f829.png)

**But it displayed from left side:**
![simulator screen shot - iphone 8 - 2018-07-09 at 10 21 31](https://user-images.githubusercontent.com/16459948/42431303-3edcf7e0-8362-11e8-983f-a01ee7d544ff.png)


**Here is the image which I am displaying**
[floorplan03-07-2018 2 (1).jpg.zip](https://github.com/huynguyencong/ImageScrollView/files/2174689/floorplan03-07-2018.2.1.jpg.zip)

**Comment by wdcurry** [comment]
Thought i had this beat, but am fighting it as well.  Setting zoomscale manually at end of DidLoad to no effect, and dropped a button that runs the same line and it works perfectly.  There is a hook somewhere that i cannot see that is keeping the zoom and offset from being set.
