### ISSUE TITLE
ContentMode Center

### ISSUE THREAD

**Issue by axiom-media** [huynguyencong/ImageScrollView#25]
If an image loaded into the ImageScrollView is smaller than the frame of the ImageScrollView, is it possible to use UIViewContentMode.center instead of stretching the image to always fill the ImageScrollView frame?  I am using the ImageScrollView to display images that my users upload, which could be very small to very large depending on what the user selects.  It would be nice is the ImageScrollView had the option to fill the frame if the image is large enough but otherwise not stretch it beyond its original size (at least until the user does a pinch to zoom).

For a regular UIView, I would try something like this:

```` swift
imageView.contentMode = UIViewContentModeCenter;
if (imageView.bounds.size.width > myView.frame.size.width) && (imageView.bounds.size.height > myView.frame.size.height) {
       imageView.contentMode = UIViewContentModeScaleAspectFit;
}
````

But this doesn't seem to have any effect on an ImageScrollView.

**Comment by tucan9389** [comment]
Do you know that it has `imageContentMode: ContentMode` property instead of use of `contentMode: UIViewContentMode`? There is own ContentMode structure.
(I don't know why use `imageContentMode: ContentMode` instead of `contentMode: UIViewContentMode`)

**Comment by tucan9389** [comment]
I think we should refactoring `ImageScrollView`'s `imageContentMode` to `UIScrollView`'s contentMode, first.

**Comment by axiom-media** [comment]
@tucan9389 yes I am aware of the imageContentMode but it does not have a .center option, which is what I am trying to highlight in my original issue.

**Comment by tucan9389** [comment]
What about uses `contentMode: UIViewContentMode`?

**Comment by tucan9389** [comment]
How about this approach?
1. Add `defaultFit` case at `ContentMode`
2. Set `minScale` to `1` if `minScale` is bigger than `1` in `setMaxMinZoomScalesForCurrentBounds()` method.
```swift
switch imageContentMode {
case .defaultFit:
    minScale = min(xScale, yScale) > 1 ? 1 : min(xScale, yScale)
// ...
}
```

It works!
If you want implementation code, check [my forked repository(ZoomableScrollView)](https://github.com/tucan9389/ZoomableScrollView).

![output](https://user-images.githubusercontent.com/37643248/39392870-f0dd40a0-4af8-11e8-82d2-c2acb17e51de.gif)

**Comment by axiom-media** [comment]
Thanks for your effort @tucan9389 but I decided to just implement my own UIImageView within a standard UIScrollView as the the ImageScrollView was giving me too many issues.  Besides this limitation on ContentMode, it doesn't seem to support device rotation properly either.  Good luck with future development!
