### ISSUE TITLE
Detect when user zoom on image

### ISSUE THREAD

**Issue by furiosFast** [huynguyencong/ImageScrollView#26]
Hi,
I would like to ask if it is possible to know when the user zooms on the image seen on the screen.
My problem is that every 5 seconds I change the image on the display and I would like this automatic transmission to stop if the user zooms on the image

Thank you

**Comment by huynguyencong** [comment]
Please use `zoomScale` property. If it is 1, it's not zooming. This view is inherited from UIScrollView.

**Comment by furiosFast** [comment]
thank you

**Comment by wdcurry** [comment]
I have created a proper protocol to enable this to happen.  I may post the solution when time permits and once i figure out how to have this control fire up zoomed and offset properly upon first load.
