### ISSUE TITLE
Load images from URL

### ISSUE THREAD

**Issue by UtkuDalmaz** [huynguyencong/ImageScrollView#3]
How can i load images from an URL ? any way to use it with SDWebImages ?

**Comment by huynguyencong** [comment]
Yes, I used it with SDWebImage. In below code, `self.imageView` is an `ImageScrollView`

```
SDWebImageManager.sharedManager().downloadImageWithURL(url, options: [], progress: { (received: Int, total: Int) -> Void in
    // Set process for loading indicator if necessary
}, completed: { (image, error, imageCacheType, isSuccess, url) -> Void in
    if error == nil {
        self.imageView.displayImage(image)
    }
})
```

**Comment by sarathsarah** [comment]
I'm using kingfisher for downloading image in background thread. how can I set it here.

**Comment by huynguyencong** [comment]
> I'm using kingfisher for downloading image in background thread. how can I set it here.

In completion closure of Kingfisher, call method `displayImage(_ :)`. The same as above example.
