### ISSUE TITLE
Adding programmaticlly using autolayout

### ISSUE THREAD

**Issue by jzeferino** [huynguyencong/ImageScrollView#31]
When adding the `ImageScrollView` programmatically using autolayout nothing shows in screen.

```swift
let imageScrollView = ImageScrollView()
self.view.addSubview(imageScrollView)
imageScrollView.translatesAutoresizingMaskIntoConstraints = false

imageScrollView.topAnchor.constraint(equalTo: self.view.topAnchor).isActive = true
imageScrollView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor).isActive = true
imageScrollView.bottomAnchor.constraint(equalTo: self.view.bottomAnchor).isActive = true
imageScrollView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor).isActive = true

imageScrollView.imageContentMode = .aspectFit
imageScrollView.initialOffset = .center

let image = UIImage(named: "moto", in: Bundle(for: type(of: self)), compatibleWith: nil)
imageScrollView.display(image: image!)
```

The weird thing in that the sample uses Storyboard to add the `ImageScrollView` and adds constraints to it.

**Comment by sabrysmk** [comment]
@jzeferino you need to initialize scrollView like this let imageScrollView = ImageScrollView(frame: self.view.bounds)

**Comment by jzeferino** [comment]
that don't make sense when using autolayout. thats the type of code one write without using autolayout. if you see the code, the constraints should make the same effect.

**Comment by muukii** [comment]
@jzeferino 
I don't know well what how is implemented inside ImageScrollView.
In your code, imageScrollView has not laid out yet.
So, even if you call `display`, it does not display the image.

Could you try to add `self.view.layoutIfNeeded` before calling `display(:)`.

**Comment by muukii** [comment]
But, If ImageScrollView handles themselves changed size, calling `layoutIfNeeded` will not solve this problem.

**Comment by huynguyencong** [comment]
> @jzeferino
> I don't know well what how is implemented inside ImageScrollView.
> In your code, imageScrollView has not laid out yet.
> So, even if you call `display`, it does not display the image.
> 
> Could you try to add `self.view.layoutIfNeeded` before calling `display(:)`.

Yes, please call `self.view.layoutIfNeeded` before `display(image:)` to make ImageScrollView adjust its size. Or call `display(image:)` in viewDidAppear.
