### ISSUE TITLE
'ContentMode' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by IvanovDeveloper** [huynguyencong/ImageScrollView#32]
After Xcode updating, I see error:
 **'ContentMode' is ambiguous for type lookup in this context**

How I can fix it?

![screen shot 2018-09-21 at 1 11 28 pm](https://user-images.githubusercontent.com/14201895/45875337-0d476580-bda0-11e8-805a-221421b9fcf0.png)

**Comment by teerayuthton** [comment]
I had the same problem.

**Comment by Mahan3340** [comment]
@teerayuthton @IvanovDeveloper 
i fixed it like below for now
 `@objc open var imageContentMode = ContentMode.widthFill`
