### ISSUE TITLE
Centering inside a NavigationController

### ISSUE THREAD

**Issue by eimermusic** [huynguyencong/ImageScrollView#34]
I had some issues with centering inside a UIPageController inside a UINavigationController. When a page is rendered it does not always know about the navigationBar and the centering can be off.

I added the following to ImageScrollView to make it render ok. A bit of a hack but it is what I ended up doing so far.

```` swift
    override open func safeAreaInsetsDidChange() {
        configureImageForSize(imageSize)
        adjustFrameToCenter()
    }
````

**Comment by muukii** [comment]
I think ImageScrollView needs to set scroll-behavior as `.never`.
`UIScrollView.ContentInsetAdjustmentBehavior`

**Comment by huynguyencong** [comment]
So you have solved your problem, haven't you?
