### ISSUE TITLE
Problem after recent update

### ISSUE THREAD

**Issue by UtkuDalmaz** [huynguyencong/ImageScrollView#36]
<img width="293" alt="screen shot 2018-10-02 at 13 09 49" src="https://user-images.githubusercontent.com/2130592/46342837-7b174b00-c644-11e8-8ae3-ef84fb32687f.png">

Having those errors after the recent update. Please check

**Comment by muukii** [comment]
That error is caused by Swift4.2.
You use Swift 4.1 when build this library. it will be passed.

**Comment by BhaktiKarva** [comment]
I tried changing swift version. But doesn't work. Still getting same errors.

**Comment by huynguyencong** [comment]
Please use version 1.5 for Swift 4.1. The new version is in order to support Swift 4.2. If you want to use version 1.6, please update your Swift version to 4.2
