### ISSUE TITLE
Supports Carthage

### ISSUE THREAD

**Issue by muukii** [huynguyencong/ImageScrollView#37]
I would like to use this library with Carthage.
But, this repo does not have a shared scheme in Xcode Project.
You can support Carthage with adding XcodeProject for Carthage and share build scheme.

**Comment by huynguyencong** [comment]
I will not support Carthage in near future. So please use Cocoapod, or install it manually by download code and add to your project. Thank you!

**Comment by eldare** [comment]
@huynguyencong Is there a specific reason why we should not expect Carthage support anytime soon? thanks.

**Comment by huynguyencong** [comment]
I have never used Carthage, so I don't have experience about it. If anyone do it, I will be ready to merge it.
