### ISSUE TITLE
delegation of scroll/zoom events.

### ISSUE THREAD

**Issue by wdcurry** [huynguyencong/ImageScrollView#39]
Unless I am missing it, there is no way to grab onto these events as-is.  It would seem I need to augment the repo for a new protocol and pass them out as needed.  If this is incorrect, please let me know, thank you.

**Comment by huynguyencong** [comment]
Sorry, currently, the code don't have any way to grab these events. I'm working on it.

**Comment by wdcurry** [comment]
It’s ok, I have managed the changes required. I’ll likely drop a repo to reflect this as time permits. Cheers!

**Comment by huynguyencong** [comment]
Please check version 1.7 for a new delegate
