### ISSUE TITLE
could you update the demo to show a set zoom level?

### ISSUE THREAD

**Issue by wdcurry** [huynguyencong/ImageScrollView#40]
It seems too challenging to achieve a simple task: fire up a viewcontroller, set an imagescrollview with a preset zoom and offset. 

I *know* i had it working before, but at present it doesn't seem to want to work.

thank you, drew..

**Comment by wdcurry** [comment]
I found the copy i had where i had the initial VC display showing a zoomed offset image, and kick me in the ass for not copying that folder before tweaking it.

The challenge with the demo is that the pod project needs a cleaning before any changes to it manifest in the running of the demo. So until you realize this, NO code changes are touched.  So.. that means that i don't know what code was being run that allowed the initial view to show a zoomed control. 

As soon as i cleaned the project, the desired result was lost.  Back to square one.

**Comment by wdcurry** [comment]
The line in private func configureImageForSize(_ size: CGSize), is the culprit:
  zoomScale = minimumZoomScale

Commenting it out provides proper behaviour for a very limited use-case.  Looking to better understand this without having to rebuild the entire repo.  This use-case, to set an initial zoom and offset, should work without complication.

**Comment by huynguyencong** [comment]
Currently, I don't have a good solution for this issue. If you set initial zoomScale, it will be reset by the first orientation change. So a workaround solution is set `imageScrollViewDelegate` (that I have just added, am going to pushed). In this function of delegate `func imageScrollViewDidChangeOrientation(imageScrollView: ImageScrollView)`, set your initial zoomScale.

```
imageScrollView.imageScrollViewDelegate = self
```

```
extension ViewController: ImageScrollViewDelegate {
	func imageScrollViewDidChangeOrientation(imageScrollView: ImageScrollView) {
               imageScrollView.zoomScale = 2
   	}
}
```

**Comment by huynguyencong** [comment]
I've just updated version 1.7, that has delegate to do that.

**Comment by wdcurry** [comment]
This would force a scale of 2 with each change, with negates the base use-case for the repo.  I have a solution in play and will revisit this as the project matures a bit more.

**Comment by huynguyencong** [comment]
Could you please share you solution?
