### ISSUE TITLE
Bug when rotate on iPad with imageContentMode = .aspectFill

### ISSUE THREAD

**Issue by ownmas** [huynguyencong/ImageScrollView#42]
https://drive.google.com/open?id=1sN3EkYHYjwO3wfYSg_vK3ZJF88KjS_iX

**Comment by ownmas** [comment]
I noticed that when changeOrientationNotification happens bounds.width and bounds.height properties is not even updated to new screen size in setMaxMinZoomScalesForCurrentBounds method

**Comment by huynguyencong** [comment]
Thanks for your feedback. I just fixed it. Please update version 1.7
