### ISSUE TITLE
Crop visible part of image on screeen

### ISSUE THREAD

**Issue by adxworld** [huynguyencong/ImageScrollView#44]
Hey, Thanks for making this library. This is what I was exactly looking for. 

I have a query. After zooming to the part of image. I wanted to create another image with the zoomed  part of the image within the boundaries of the screen. Like cropping the part that's visible on screen.

How can I get that? I want to save that in a image object and display that later.

**Comment by adxworld** [comment]
Managed to do it myself. But if this is the response. This library doesnt deserve to be live. Take it off the github

**Comment by adxworld** [comment]
Anything yet?

**Comment by huynguyencong** [comment]
Sorry, but it is not a function of this library. This is a library for Zooming and Scrolling image. Please implement it by yourself. Thank you!

**Comment by himanshujamnaniopenxcell** [comment]
Library is amazing but if it is not returning cropped image then it is worth less
