### ISSUE TITLE
compile in swift 5

### ISSUE THREAD

**Issue by oeresundsgruppen** [huynguyencong/ImageScrollView#48]
2 compile errs in swift 5 - can you fix ?

    private func initialize() {
        showsVerticalScrollIndicator = false
        showsHorizontalScrollIndicator = false
        bouncesZoom = true
        decelerationRate = UIScrollView.DecelerationRate.hash
        delegate = self
        
        NotificationCenter.default.addObserver(self, selector: #selector(ImageScrollView.changeOrientationNotification), name: UIDevice.NSNotification.Name.UIDeviceOrientationDidChange, object: nil)
    }

**Comment by huynguyencong** [comment]
Have you updated to latest version? I have update it to Swift 5. Please update your pod. Run below command:

`pod update 'ImageScrollView'`

**Comment by Algalish** [comment]
@huynguyencong  Hi. It looks like the source here at github is updated to Swift 5 but the CocoaPod is still on the previous version. So every time I update pods I have to set the swift version for this pod to 4.2 or 5 manually. Can you please push the latest version to the CocoaPods ? Thank you very much!

**Comment by huynguyencong** [comment]
Thanks for your report. I have just updated the CocoaPod version to 1.9.
