### ISSUE TITLE
Images look very small

### ISSUE THREAD

**Issue by UtkuDalmaz** [huynguyencong/ImageScrollView#5]
Hello,

It works good when i zoom in or out but at first images look very small.

Check screenshot please 
![img_3029](https://cloud.githubusercontent.com/assets/2130592/16521270/6e347ed2-3f9e-11e6-9f18-b4a2c528549c.PNG)

How can i fix it ?

**Comment by huynguyencong** [comment]
What is image size and view size?

**Comment by UtkuDalmaz** [comment]
Image size is iphone 6 screenshot, view size is full screen on storyboard

**Comment by huynguyencong** [comment]
Please update new 1.2 version and tell me this bug happen again or not
