### ISSUE TITLE
Change orientation suggestion

### ISSUE THREAD

**Issue by laindow** [huynguyencong/ImageScrollView#50]
Hello,

    I just want to offer you a bit better way to handle size changes. You right frames change not triggered if you change orientation or if autolayouts updated for example :) But bounds definitely got that events :) 
   You can easy to handle that by this code

    override var bounds: CGRect {
        didSet {
            //Update UI if size of view changed
            if (usedWidth != bounds.width) || (usedHeight != bounds.height)  {
                reloadUI()
            }
        }
    }

    private func reloadUI() {

        usedWidth = bounds.width
        usedHeight = bounds.height
    }

  Something like that. I can make real code for you if you want. Thanks for your small and good library :)
  Just one more suggestion make imageSize public :) at least for read access :)

**Comment by huynguyencong** [comment]
Sorry this approach is not work. I have tried it, but it had many problems, like recurring function call.
