### ISSUE TITLE
Using programmatically without storyboard 

### ISSUE THREAD

**Issue by rogeriowiethornjr** [huynguyencong/ImageScrollView#53]
Can I use like this?
let imageScrollView = ImageScrollView()
self.view.addSubview(imageScrollView)
imageScrollView.setup()
imageScrollView.display(image: image)

**Comment by bstillitano** [comment]
You'd need to set your constraints and add your view to its subview then call the `display()` and `setup()` functions.

**Comment by huynguyencong** [comment]
Remember to call display(image:) function after view is layouted.
