### ISSUE TITLE
Image position is reset after tilt

### ISSUE THREAD

**Issue by fedorpashin** [huynguyencong/ImageScrollView#55]
Position of an image is always reset when I tilt forward an iPhone. The problem disappeared when I commented this line: https://github.com/huynguyencong/ImageScrollView/blob/aea864b221423dc8fd375b5997f110f1008e6dbd/Sources/ImageScrollView.swift#L80

**Comment by huynguyencong** [comment]
Sorry, image position will be reset when device is rotate, because screen size changed.
