### ISSUE TITLE
Landscape Image not centered vertically (iOS 13.3)

### ISSUE THREAD

**Issue by bennettl** [huynguyencong/ImageScrollView#57]
Trying to use this inside a navigation controller, image is not centered vertically. On iOS 13.3

![Screen Shot 2020-06-10 at 7 24 08 PM](https://user-images.githubusercontent.com/1672224/84338148-33063680-ab50-11ea-9dfa-55d7c7cfcdc4.png)

**Comment by huynguyencong** [comment]
I can't reproduce. In the demo project, it is center vertically. If your project does not have any private thing, please send me so I can debug to fix it. Thank you.

**Comment by bilaalrashid** [comment]
Do you also experience this issue with portrait images or does it only happen with landscape images? I've also experienced this and think it may be related to `UINavigationController` but it happens to me regardless of what image I use.

**Comment by huynguyencong** [comment]
I just update new version 1.9.1 that fix this bug. It is not related to UINavigationController. It happen because displayImage is called when frame is not updated.
