### ISSUE TITLE
DidChangeOrientation is fired when notification bar is swiped down

### ISSUE THREAD

**Issue by Bartson** [huynguyencong/ImageScrollView#60]
Hi, 
I realized that DidChangeOrientation event is fired when I swipe down notification bar. Is it intentional? Can I somehow block that event?

**Comment by Bartson** [comment]
DidChangeOrientation seems buggy. In some situations it triggered randomly and was broking app behaviour. For temporary fix I just commented this line in ImageScrollView.swift:
`NotificationCenter.default.addObserver(self, selector: #selector(ImageScrollView.changeOrientationNotification), name: UIDevice.orientationDidChangeNotification, object: nil)`

My app is always portrait so I don't really need this.

**Comment by bjravalet** [comment]
@Bartson I have the same issue! Thanks for sharing your hack

For those who don't wan't to fork or modify the library's code, here is another hack:
```
@IBOutlet private weak var imgScrollView: ImageScrollView!

override func viewDidLoad() {
     super.viewDidLoad()
     NotificationCenter.default.removeObserver(self.imgScrollView)
}
```

This is ok until other useful elements would be added to the NotificationCenter, so far it seems the orientation is the only notification it's listening to!
I still don't understand how the app could be portrait only but the pod is still catching this event.

**Comment by huynguyencong** [comment]
It is not intentional. Maybe it is iOS bug. I can't reproduce it. How offen do you have this problem?
