### ISSUE TITLE
May I know the purpose of 0.999 technique?

### ISSUE THREAD

**Issue by yccheok** [huynguyencong/ImageScrollView#66]
Thank you for this useful library. It saves me countless of hour to implement a zoomable and swipeable image viewer.

However, I am very curious on the following line

https://github.com/huynguyencong/ImageScrollView/blob/master/Sources/ImageScrollView.swift#L248

It seems to me, without 0.999 technique, it will become problematic when this `ImageScrollView` is placed within `UIPageViewController`.

I try to implement such, by placing `ImageScrollView` in `UIPageViewController`

https://gist.github.com/yccheok/b660cc09b404ae3bab3eb4a586c33cc8

However, I do not find any issue, when I try to change line 248

from

`minimumZoomScale = minScale * 0.999`

to

`minimumZoomScale = minScale`

![ezgif com-gif-maker](https://user-images.githubusercontent.com/308276/130367704-7f7f6a0d-ba15-4055-aced-a335ad05fc84.gif)

May I know, what problem 0.999 is trying to solve?

Thank you very much

**Comment by huynguyencong** [comment]
Hmm, maybe the problem has been fixed by Apple in the new SDK. I am sure it was a problem in the past, because I happened in my project, and I fixed it by that workaround. If you don't see any problem when removing the multiply, continue using it with that removal.
