### ISSUE TITLE
Minor issue with documention

### ISSUE THREAD

**Issue by rpbrokaw** [huynguyencong/ImageScrollView#7]
Just starting to test this control.

Noticed when I was setting it up that when you edit the custom class for the ScrollView control you need to set both the Class and the Module to ImageScrollView. If you set only the Class the control crashes at runtime.

Note that the Readme file shows a graphic and only visually boxes the Class. Would be useful and more accurate to have the box highlight both the Class and the Module to avoid the above error.

Looking forward to playing with the control.

**Comment by huynguyencong** [comment]
Because I found that Module is auto fill after I set Class. But I noted it, and change docs now, to prevent the case that Module is not auto fill.
Thank for your contribution
