### ISSUE TITLE
ios 10 swift 3

### ISSUE THREAD

**Issue by tahaSuleyman** [huynguyencong/ImageScrollView#9]
Are you planning to add a new version for swift 3?

**Comment by nelson-chim** [comment]
I have made a pull request for swift 3 support, you may try the pod with my repo, until @huynguyencong accept the pull request

**Comment by huynguyencong** [comment]
I'm reviewing @derek-chim pull request. Merge it as soon as posible. Thank you

**Comment by nelson-chim** [comment]
Thanks
